
install:
  # Check the python version: 
  - "python.exe --version"

build: false  # Not a C# project

test_script:
  # Build the compiled extension and run the project tests
  - "python.exe scratch/test/test_pyflow.py"

branches:
  only:
    - master
    - travis
    - /v\d\.\d\.\d/

notifications:
  - provider: Email
    to:
      - csaunders@illumina.com
