language: python

matrix: 
  include: 
    - os: linux
      sudo: required
      python: "2.7"
    - os: linux
      sudo: required
      python: "2.6"

before_install:
  - date -u
  - uname -a
  - lsb_release -a

install:
  - python -V

script:
  - cd scratch/test && bash ./test_release_tarball.bash -nosge 

branches:
  only:
    - master
    - travis
    - /v\d\.\d\.\d/

notifications:
  email:
    recipients:
      - csaunders@illumina.com
